-- MySQL Script generated by MySQL Workbench
-- sáb 04 out 2025 17:33:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Movies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imdbID` VARCHAR(20) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `year` SMALLINT(4) NOT NULL,
  `decade` SMALLINT(4) NOT NULL,
  `plot` TEXT NULL,
  `genre` VARCHAR(255) NULL,
  `rated` VARCHAR(10) NULL,
  `runtime` VARCHAR(20) NULL,
  `director` VARCHAR(255) NULL,
  `actors` VARCHAR(512) NULL,
  `poster` VARCHAR(512) NULL,
  `imdbRating` DECIMAL(3,1) NULL,
  `ratings` JSON NULL,
  `type` VARCHAR(20) NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `imdbID_UNIQUE` ON `mydb`.`Movies` (`imdbID` ASC) VISIBLE;

CREATE INDEX `decade_index` ON `mydb`.`Movies` (`decade` ASC) VISIBLE;

CREATE INDEX `year_index` ON `mydb`.`Movies` (`year` ASC) VISIBLE;

CREATE INDEX `type` ON `mydb`.`Movies` (`type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Favorites` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movies_id` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `deletedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Favorites_Movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `mydb`.`Movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Favorites_Movies1_idx` ON `mydb`.`Favorites` (`movies_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `movies_id_UNIQUE` ON `mydb`.`Favorites` (`movies_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reviews` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `comment` TEXT NULL,
  `rating` DECIMAL(2,1) NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `deletedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Reviews_Movies1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`Movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Reviews_Movies1_idx` ON `mydb`.`Reviews` (`movie_id` ASC) VISIBLE;

CREATE INDEX `updated_index` ON `mydb`.`Reviews` () VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`SearchHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SearchHistory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SearchHistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movies_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `query` VARCHAR(255) NULL,
  `year` SMALLINT(4) NOT NULL,
  `decade` SMALLINT(4) NOT NULL,
  `genre` VARCHAR(255) NULL,
  `type` VARCHAR(20) NULL,
  `searchedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_SearchHistory_Movies`
    FOREIGN KEY (`movies_id`)
    REFERENCES `mydb`.`Movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SearchHistory_Movies_idx` ON `mydb`.`SearchHistory` (`movies_id` ASC) VISIBLE;

CREATE INDEX `year_index` ON `mydb`.`SearchHistory` (`year` ASC) VISIBLE;

CREATE INDEX `decade_index` ON `mydb`.`SearchHistory` (`decade` ASC) VISIBLE;

CREATE INDEX `genrer_index` ON `mydb`.`SearchHistory` (`genre` ASC) VISIBLE;

CREATE INDEX `type_index` ON `mydb`.`SearchHistory` (`type` ASC) VISIBLE;

CREATE INDEX `createdAt_index` ON `mydb`.`SearchHistory` (`searchedAt` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
